## Heartbeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/heartbeat.docker.yml
#

name: heartbeat

heartbeat.monitors:
  # - type: http
  #   schedule: "@every 5s"
  #   urls:
  #     - http://elasticsearch:9200
  #   username: heartbeat_internal
  #   password: heartbeat
  #
  # - type: icmp
  #   schedule: "@every 5s"
  #   hosts:
  #     - elasticsearch

  - type: http
    schedule: "@every 5s"
    urls: ["http://www.google.com"]
    service.name: google-service
    id: google-id
    name: google

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: heartbeat

output.elasticsearch:
  hosts: [http://elasticsearch:9200]
  username: heartbeat_internal
  password: heartbeat

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/heartbeat/current/http-endpoint.html
#

http:
  enabled: true
  host: 0.0.0.0
